version: '3'
services:
  dj:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - mynet

      